name: Release
# trigger on push to master
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    name: Push to Kapeta Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/checkout@v3
        id: checkout
      - uses: actions/setup-node@v3
        id: setup-node

      - name: Push to Kapeta Cloud
        id: kapeta-registry-push
        uses: kapetacom/core-registry-action@v1
        with:
          credentials: ${{ secrets.KAPETA_TOKEN }}
          action: 'push'

      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.0.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
